networks:
  quiz-hoster:
    external: true

services:
  db:
    build:
      context: ./database
    container_name: postgres-raze
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: quiz-hoster-postgres-dev
    networks:
      - quiz-hoster
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgres/data
  server:
    build:
      context: ./server
      dockerfile: dev.server.Dockerfile
    container_name: server-sage
    depends_on:
      - db
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_MODE: ${FLASK_MODE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: quiz-hoster-server-dev
    networks:
      - quiz-hoster
    tty: true
    volumes:
      - ./server:/usr/src/app
  server_reverse_proxy:
    build:
      context: ./server
      dockerfile: server-reverse-proxy.Dockerfile
    container_name: server-reverse-proxy-fade
    depends_on:
      - server
    image: quiz-hoster-server-reverse-proxy-dev
    networks:
      - quiz-hoster
    volumes:
      - ./server/nginx-dev:/etc/nginx
  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    container_name: client-yoru
    depends_on:
      - server_reverse_proxy
    environment:
      VITE_SERVER_URL: http://172.19.0.4
    image: quiz-hoster-client
    networks:
      - quiz-hoster
    tty: true
    volumes:
      - ./client:/home/node/app

volumes:
  postgres-data:
