networks:
  quiz-hoster:
    external: true

services:
  db:
    build:
      context: ./database
    container_name: postgres-raze
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: quiz-hoster-postgres-prod
    networks:
      - quiz-hoster
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgres/data
  server:
    build:
      context: ./server
      dockerfile: server.Dockerfile
    container_name: server-sage
    depends_on:
      - db
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_MODE: ${FLASK_MODE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: quiz-hoster-server-prod
    networks:
      - quiz-hoster
  server_reverse_proxy:
    build:
      context: ./server
      dockerfile: server-reverse-proxy.Dockerfile
    container_name: server-reverse-proxy-fade
    depends_on:
      - server
    image: quiz-hoster-server-reverse-proxy-prod
    networks:
      - quiz-hoster
  static_assets_server:
    build:
      context: ./client
    container_name: static-assets-server-gecko
    depends_on:
      - server_reverse_proxy
    image: quiz-hoster-static-assets-server
    networks:
      - quiz-hoster
  reverse_proxy:
    build:
      context: .
    container_name: reverse-proxy-skye
    depends_on:
      - static_assets_server
    image: quiz-hoster-reverse-proxy
    networks:
      - quiz-hoster
    ports:
      - 80:80

volumes:
  postgres-data:
